name: app01
recipe: drupal9
config:
  webroot: web
  php: 7.4
  via: apache:2.4
  database: mariadb:10.4
  xdebug: false
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
tooling:
  refresh-drupal:
    service: appserver
    description: Refreshes Drupal. Useful after db import
    cmd: drush updb -y ; drush cim -y ; drush cr
