<?php

/**
 * @file
 * Primary module hooks for youtube video formatter module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

 function youtube_video_formatter_theme($existing, $type, $theme, $path) {
   return [
     'youtube_video' => [
       'variables' => [
         'youtube_id' => NULL,
         'width' => 540,
         'height' =>315,
         'allowFullScreen' =>1,
       ],
     ],
   ];
 }